#!/usr/bin/env python3
"""
00_run_all.py
=============
Runs the analysis pipeline in order and stops at the first failure.

STAGES
    A  Acquire      external data downloads (network required)
    B  Build        assemble the county-level analytic dataset
    C  Analyse      descriptive statistics and regression models
    D  Validate     recompute every manuscript number and check the paper
    E  Present      figures, Word tables, and publication outputs

USAGE
    python code/00_run_all.py                 analysis + validation (default)
    python code/00_run_all.py --with-acquire  also re-download source data
    python code/00_run_all.py --with-present  also rebuild figures and tables
    python code/00_run_all.py --all           everything

REPRODUCING THE PUBLISHED RESULTS
    The analytic dataset is committed, so the default run reproduces every
    number in the manuscript without any network access. Stage A is only needed
    to rebuild the inputs from their original sources, and stage E needs the
    county geometry file, which is too large for GitHub and is regenerated by
    stage B.
"""

import argparse
import os
import subprocess
import sys
import time

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CODE_DIR = os.path.join(BASE_DIR, "code")

ACQUIRE = [
    ("01_download_datasets.py", "Download SVI, RUCC, TIGER, ZIP crosswalk"),
    ("01b_fetch_census_population.py", "Fetch ACS population (needs a Census API key)"),
]
BUILD = [
    ("02_build_analytic_dataset.py",
     "Build county_analytic_dataset.csv and the facility mapping audit"),
]
ANALYSE = [
    ("03_descriptive_analysis.py", "Descriptive statistics, Table 1"),
    ("05_regression_analysis.py", "SVI negative binomial models"),
    ("06_edi_sensitivity_analysis.py", "Construct the EDI, fit adjusted models"),
    ("09_validated_index_sdi.py", "External validation with the Graham Center SDI"),
    ("13_model_specification.py", "Poisson vs NB, estimated vs fixed dispersion"),
    ("14_accredited_only_sensitivity.py", "Accredited-only cohort sensitivity"),
]
VALIDATE = [
    ("12_manuscript_numbers.py", "Recompute every manuscript number and check the paper"),
]
PRESENT = [
    ("04_choropleth_map.py", "Figure 1A choropleth"),
    ("08_svi_edi_comparison_maps.py", "Figures 2 and 3"),
    ("10_forest_plots.py", "Figure 1B and Figure S forest plots"),
    ("11_edi_tables_and_stats.py", "Word tables and supplementary statistics"),
    ("07_publication_outputs.py", "Publication figure 1 and Table 1"),
]


def run_stage(name, scripts, failures):
    if not scripts:
        return
    print()
    print("=" * 72)
    print(f"  STAGE {name}")
    print("=" * 72)
    for script, description in scripts:
        path = os.path.join(CODE_DIR, script)
        if not os.path.exists(path):
            print(f"  SKIP  {script:38s} (not found)")
            continue
        print(f"  RUN   {script:38s} {description}")
        t0 = time.time()
        result = subprocess.run([sys.executable, path], cwd=BASE_DIR,
                                capture_output=True, text=True)
        elapsed = time.time() - t0
        if result.returncode != 0:
            print(f"  FAIL  {script} (exit {result.returncode}, {elapsed:.1f}s)")
            tail = (result.stderr or result.stdout).strip().splitlines()[-12:]
            for line in tail:
                print(f"        {line}")
            failures.append(script)
            return
        print(f"  OK    {script:38s} {elapsed:.1f}s")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--with-acquire", action="store_true",
                    help="re-download source data (network required)")
    ap.add_argument("--with-present", action="store_true",
                    help="rebuild figures, tables, and publication outputs")
    ap.add_argument("--all", action="store_true", help="run every stage")
    args = ap.parse_args()

    do_acquire = args.with_acquire or args.all
    do_present = args.with_present or args.all

    failures = []
    run_stage("A  ACQUIRE", ACQUIRE if do_acquire else [], failures)
    if not failures:
        run_stage("B  BUILD", BUILD if do_acquire else [], failures)
    if not failures:
        run_stage("C  ANALYSE", ANALYSE, failures)
    if not failures:
        run_stage("D  VALIDATE", VALIDATE, failures)
    if not failures and do_present:
        run_stage("E  PRESENT", PRESENT, failures)

    print()
    print("=" * 72)
    if failures:
        print(f"  PIPELINE FAILED at {failures[0]}")
        print("=" * 72)
        sys.exit(1)
    print("  PIPELINE COMPLETE")
    print("=" * 72)
    print("  Key outputs")
    print("    data/processed/county_analytic_dataset.csv   one row per US county")
    print("    output/validation/manuscript_numbers.txt     every number in the paper")
    print("    output/validation/manuscript_check.txt       paper vs data, cell by cell")
    print("    output/results/                              model results, machine-readable")
    print("    data/processed/facility_mapping_audit.csv    every source record, mapped or excluded")
    print("    output/validation/facility_reconciliation.txt facility counts reconciled to source")
    print("    output/tables/                               Word tables")
    if not do_present:
        print()
        print("  Figures and Word tables were not rebuilt. Use --with-present for those.")


if __name__ == "__main__":
    main()
